### ISSUE TITLE
Allow reversability of keypad grid

### ISSUE THREAD

**Issue by dbgrey44** [janten/keypad-layout#17]
Hi,
The app is really great, but seems less intuitive since  normal person would mostly be comfortable with standard keypad with 1 in top left and 9 on bottom right.
It would be very cool if you can just add this feature to allow folks to reverse it if they want.

**Comment by fiveNinePlusR** [comment]
I am not aware of any keypad that uses that layout other than a telephone... this seems like it would only fill a very small niche of people that are used to a telephone numpad and not a keyboard numpad.

**Comment by meera-gd** [comment]
For people using a macbook or who don't have a keypad, the 7-at-the-top has no mapping to anything visually and also has no advantages in terms of keypresses. I like the idea of allowing 1 at the top.

**Comment by janten** [comment]
I am with @fiveNinePlusR on this one and will not implement this. You may always fork this project to make it suit your own need, though.
