### ISSUE TITLE
use the same number twice to maximize window

### ISSUE THREAD

**Issue by jaroet** [janten/keypad-layout#18]
Hello,

As I would like to work in maximized windows (not fullscreen) I am hitting CTRL 1 and 9 alot. Working on a MacBook Pro this is a lot of hand movement at the moment. 

Could you implement that when the same number is pressed twice that this is interpreted as to maximize the screen (or mayby configurable)

Jeroen

**Comment by janten** [comment]
Hi Jeroen,
this change would conflict with the current behavior so I will close this issue and leave it unfixed. You can still save some hand movement by pressing <kbd>Ctrl</kbd>, <kbd>0</kbd>, and <kbd>5</kbd> instead, which has the same effect.
