### ISSUE TITLE
Window Scaling with Dock on Side

### ISSUE THREAD

**Issue by pixelakrobat** [janten/keypad-layout#19]
If the MacOS Dock is not located at the bottom, but on the side, this is not taken into account for window scaling.

**Comment by pixelakrobat** [comment]
![example](https://user-images.githubusercontent.com/7656788/39237565-2fa1709c-487c-11e8-8243-714dbc2182ae.png)

**Comment by janten** [comment]
This should be fixed in [Keypad Layout 1.7](https://github.com/janten/keypad-layout/releases/tag/1.7).

**Comment by pixelakrobat** [comment]
THX a lot!
