### ISSUE TITLE
Support for multiple screens

### ISSUE THREAD

**Issue by janten** [janten/keypad-layout#2]
Simply using `[NSScreen mainScreen]` calculates incorrect regions.

**Comment by janten** [comment]
Fixed in ef413e430d9f8e89c192a1e2b474796a9bdadda1.

**Comment by Abu-Daud** [comment]
so it works good on 2 screens?  how do the 1-9 regions map to the second screen?

**Comment by janten** [comment]
It works for all screens independently. A window cannot span multiple screens.

**Comment by Abu-Daud** [comment]
Thank you.  I see the bottom left corner is region 1.  If I want to move my tiny safari window from the bottom left of my left screen to full screen on the right screen, what are the key presses?

**Comment by janten** [comment]
There's no way to do this with this utility at the moment. You can only resize and reposition a window on the screen it's already on. Sorry.
