### ISSUE TITLE
Version 1.8 binary doesn't open in macOS 11

### ISSUE THREAD

**Issue by popularsizzle** [janten/keypad-layout#23]
Installed via homebrew, the follow error is shown when launching:
<img width="372" alt="Screen Shot 2021-01-10 at 10 49 56 am" src="https://user-images.githubusercontent.com/16108823/104111010-95672580-5331-11eb-959e-3ae22c5e2533.png">
Perhaps a similar issue to #8.

**Comment by janten** [comment]
Keypad Layout is not notarized by Apple, which causes this message to appear. It should open just fine if you right-click and choose "Open" from the context menu. After doing this once, you should be able to start it like any other application.

Notarization requires a paid membership in the Apple Developer Program and I don't really see myself paying 99 dollars just to remove this warning, sorry.

**Comment by janten** [comment]
If you are using homebrew, `brew install --no-quarantine keypad-layout` will also do the trick.

**Comment by popularsizzle** [comment]
No problem.
