### ISSUE TITLE
Starting from launcher does not work, but from terminal, it does work

### ISSUE THREAD

**Issue by arnoFleming** [janten/keypad-layout#24]
I am too unfamiliar with naming conventions for apps on MacOS, therefore, the title of this issue may be not as descriptive as it could be, but here it goes:

I am on Big Sur, with an Intel processor.

Starting the app from the launcher, starts it, but it doesn't function
Starting the app from the terminal with `open /Applications/Keypad\ Layout.app` does the same thing
Starting the app from the terminal with `/Applications/Keypad\ Layout.app/Contents/MacOS/Keypad\ Layout`, it does function

What can I do to fix this?

Below a somewhat wordy way of what I said above, with a lot more detail

Background: I've installed Keypad Layout using `brew install --no-quarantine keypad-layout`

Given I am on Mac OS Big Sur, on a MacBookPro13, Dual-Core Intel Core i5 
When I use the launcher to start Keypad Layout
The program starts and the icon is shown in my menu bar
When I select a program 
And do the key combo control-0-5
I expect the program to become full screen
But the program does not become full screen

Given I am on Mac OS Big Sur, on a MacBookPro13, Dual-Core Intel Core i5 
When I run `open /Applications/Keypad\ Layout.app` from the terminal
The program starts and the icon is shown in my menu bar
When I select a program 
And type the key combo control-0-5
I expect the program to become full screen
But the program does not become full screen

Given I am on Mac OS Big Sur, on a MacBookPro13, Dual-Core Intel Core i5 
When I run `/Applications/Keypad\ Layout.app/Contents/MacOS/Keypad\ Layout` from the terminal
The program starts and the icon is shown in my menu bar
When I select a program 
And type the key combo control-0-5
Then the program becomes full screen

**Comment by janten** [comment]
Terminal probably has access to the Accessibility framework and Keypad Layout does not. Open System Preferences, click Security & Privacy, click Privacy, click Accessibility, then select the app's checkbox. Apple.com has a [detailed description](https://support.apple.com/guide/mac-help/allow-accessibility-apps-to-access-your-mac-mh43185/mac) of all steps.

**Comment by arnoFleming** [comment]
Thanks for your help. 

I did follow all these steps (before), and re-followed them today. 

This didn't resolve the issue. 

I can confirm that my terminal (iTerm2) indeed has access to the accessibility framework, but so does Keypad Layout. 

/me none the wiser. I prolly fouled up something ¯\\\_(ツ)_/¯

I will keep using it as is - it is the best tool for the job, I'd be happy to debug this further. Please close this if you feel no need. Running it from a terminal and backgrounding it works fine for me :D 

Arno

**Comment by janten** [comment]
I running out of ideas here. I'll leave this issue open and see if anybody else has the same problem.

**Comment by VanBronckhorst** [comment]
I had the same problem after the Big Sur update. The accessibility checkbox was not working for me (I could not toggle it off).

I ran `tccutil reset Accessibility`, re-enabled the Accesibility checkbox, and it started working again

**Comment by arnoFleming** [comment]
I'm on Big Sur as well. Too bad it doesn't resolve my issue. Let's still blame it on my setup  (it _doesn't_ work on my machine)

**Comment by goryakon** [comment]
Can you please tell, can I change ctrl-button to another button like cmd or shift or any other?

**Comment by arnoFleming** [comment]
It again started acting up today. I'm on a new machine. I've installed a lot of the same tools as on the previous Mac, so I'm blaming myself: It's how my setup is... set up.

**Comment by arnoFleming** [comment]
Most notably I think the interaction between espanso (snippet substitution) keypad-layout and MacOS (Montery, Version 12.5.1) is working.
