### ISSUE TITLE
Changed code signature in version 1.11?

### ISSUE THREAD

**Issue by suschizu** [janten/keypad-layout#26]
hello @janten - I've noticed that the code signature has changed in the latest release:

EXPECTED 'Jan-Gerd Tenberge (M694M84694)' 
FOUND 'Jan-Gerd Tenberge (7KV498VKRZ)'

can you confirm it? thanks

**Comment by janten** [comment]
That is correct, I did not renew my developer subscription at some point and now got a new one, including a new team identifier.

**Comment by suschizu** [comment]
great thanks for the quick response! happy new year
