### ISSUE TITLE
Make `brew` installable

### ISSUE THREAD

**Issue by Miserlou** [janten/keypad-layout#3]
This is a really handy application, I'd love it if there were the ability to install with `homebrew`!

**Comment by janten** [comment]
I have created a [brew cask pull request](https://github.com/caskroom/homebrew-cask/pull/34135) for Keypad Layout to be installable with `brew cask install keypad-layout`.

**Comment by janten** [comment]
Merged.

**Comment by Fusion** [comment]
Please add to the README the need to first tap the formula:

    brew tap koekeishiya/formulae
