### ISSUE TITLE
Split screen

### ISSUE THREAD

**Issue by ttunguz** [janten/keypad-layout#4]
It would be awesome to have a split screen mode (50/50). Love the product. Super fast.

**Comment by fordnox** [comment]
same here. Split vertical/horizontal is whats missing

**Comment by janten** [comment]
Any ideas for an obvious/discoverable key combination for this?

**Comment by erik-stephens** [comment]
These come to mind:

`(`: left half
`)`: right half
`-`: upper half
`_`: lower half

**Comment by ttunguz** [comment]
Brilliant

**Comment by janten** [comment]
On my German keyboard layout these do not make much sense and need an additional modifier key. An ideal solution would stick to the numeric keypad. Something like `Ctrl` + `Shift` + [`7`, `8`, `4`, `5`] may work as a selector for screen quadrants instead of thirds but is also not very intuitive.

**Comment by ttunguz** [comment]
Would 01 02 03 04 work?

**Comment by daan-nguyen** [comment]
Could keep the keypad layout approach but use an extra key like above, something like:

`04`, `44`: left half
`06`, `66`: right half
`08`, `88`: top half
`02`, `22`: bottom half

You could then do similar with corners too to get a quartered layout (1, 3, 7, 9)

**Comment by ghost-pre** [comment]
I'd love split screen as well, but I really like the simplicity of this app; adding in a lot of different key combinations takes away from that slightly.

A compromise might be allowing users to set their own combinations in a `~/.keypad-layout.yaml` file. I suggest the following format:

    key_combo:
      - [from_x_%, from_y_%]
      - [to_x_%, to_y_%]

E.g. for the initially suggested left/right half combos:

    (:
      - [0, 0]
      - [50, 100]
    ):
      - [50, 0]
      - [100, 100]

This means users with international keyboard layouts aren't excluded by hard-coded defaults for all the various options people want.

It also means you might be able to override the default numeric combinations.

**Comment by janten** [comment]
Split screen functionality has been added in Keypad Layout 1.5.
