### ISSUE TITLE
Support for 10.10/10.11?

### ISSUE THREAD

**Issue by Miserlou** [janten/keypad-layout#5]
I'm on an old OSX, any chance of support for old OSX? :)

**Comment by Miserlou** [comment]
Currently gives `LSOpenURLsWithRole() failed with error -10825 for the file /Applications/Keypad Layout.app.`

**Comment by janten** [comment]
A pull request for this would be very welcome. Simply setting the deployment target to 10.10 does not seem to suffice and I do not have a full 10.10 development environment around.

**Comment by VanBronckhorst** [comment]
I do have the 10.10 sdk on my mac, and I managed to build and run the app with minimal changes. 
I made a [branch on my forked repository](https://github.com/VanBronckhorst/keypad-layout/tree/mac-version-downgrade) with it. I'm not sure you will be able to build it on you mac though (I'm not exactly an expert in mac app deployment). Should I just go ahead with the pull request?

**Comment by janten** [comment]
Yes please.

**Comment by janten** [comment]
This has been included in Keypad Layout 1.3.
