### ISSUE TITLE
Version 1.2 Release Binary doesn't open

### ISSUE THREAD

**Issue by rmateu** [janten/keypad-layout#8]
Seems like v1.2 binary has a release issue. Installing v1.1 works great.

## Steps to Reproduce
1. Download 1.2 binary from releases
2. Launch via right-click and Open to bypass signed app security

**Expected:** 
- Apps Launches

**Actual:** 
- OS prompt: "Keypad Layout" can't be opened. You should move it to the Trash
![keypad](https://cloud.githubusercontent.com/assets/879149/26313287/62d35f74-3ed8-11e7-8ebd-8155edc59800.png)

Tested on two Mac's with 10.12.

**Comment by daan-nguyen** [comment]
I get a similar problem as well after it failed to find it on `brew cask`

**Comment by janten** [comment]
This should be fixed in version 1.3, the release was seemingly signed using the wrong certificates. Sorry for the inconvenience.
